name: Build and Analyze

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - uses: actions/checkout@v4

      # 2. Instalar JDK 24 (Temurin)
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      # 3. Dar permisos de ejecución a gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Compilar con Gradle (forzamos a usar JAVA_HOME del setup-java)
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          ORG_GRADLE_JAVA_HOME: ${{ env.JAVA_HOME }}

      # 5. Análisis con SonarCloud (nuevo action recomendado)
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
