# SONAR CLOUD
name: SonarCloud Scan
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

            # 🔑 Crear archivo de credenciales Firebase
      - name: Set up Firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_01 }}" > $GITHUB_WORKSPACE/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-key.json" >> $GITHUB_ENV

      # ✅ Build con tests habilitados
      - name: Build with Gradle (with tests)
        run: ./gradlew clean build --no-daemon

      # 🚀 Escaneo SonarCloud (recoge resultados de test y cobertura)
      - name: Run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
