name: SonarCloud Scan

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 👇 Instala Java 24 (EA build disponible en Adoptium/Temurin)
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: gradle

      - name: Verify Java version
        run: java -version

      # 🔑 Fix permisos de gradlew
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # 👇 Aquí Gradle ya usará el JDK 24 instalado (saltando tests)
      - name: Build with Gradle (skip tests)
        run: ./gradlew clean build -x test --no-daemon

      # 👇 Escaneo SonarCloud
      - name: Build project
      - name: Run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
