name: SonarCloud Scan
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Set up Firebase config
        run: echo "FIREBASE_CONFIG_03=${{ secrets.FIREBASE_CONFIG_03 }}" >> $GITHUB_ENV

      - name: Build + tests + coverage + SonarCloud
        env:
          FIREBASE_CONFIG_03: ${{ secrets.FIREBASE_CONFIG_03 }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: ./gradlew clean build jacocoTestReport sonarqube --refresh-dependencies --no-daemon
