name: SonarCloud Scan
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      # Build sin tests para evitar fallos de Firebase
      - name: Build with Gradle (skip tests)
        run: ./gradlew clean build -x test --no-daemon

      # 👇 Escaneo SonarCloud
      - name: Build project
        run: ./gradlew clean build
      - name: Run SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          FIREBASE_CONFIG_01: ${{ secrets.FIREBASE_CONFIG_01 }}
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
